model:
  base_learning_rate: 5.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    beta_schedule: cosine
    cosine_s: 0.008
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 64
    channels: 3
    cond_stage_key: coords
    cond_stage_trainable: false
    conditioning_key: hybrid
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 6
        out_channels: 3
        model_channels: 480
        attention_resolutions:
        - 8
        - 4
        num_res_blocks: 2
        channel_mult:
        - 1
        - 1
        - 1
        - 1
        num_heads: 2
        dropout: 0.16
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 12288
        ckpt_path: models/first_stage_models/sneaker/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.00
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder2
      params:
        embed_dim: 512
        key: coords
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    num_workers: 6
    wrap: false
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: training.txt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: validation.txt
        size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 10000000
        max_images: 2
        increase_log_steps: False

  trainer:
    benchmark: True
